import type { NodeConfig, NodeType } from "@/types";

export const NODE_REGISTRY: Record<NodeType, NodeConfig> = {
  openai: {
    label: "OpenAI",
    description: "GPT-4o language model",
    category: "ai",
    icon: "Brain",
    color: "#10A37F",
    inputs: 1,
    outputs: 1,
    defaultData: { model: "gpt-4o", temperature: 0.7, maxTokens: 4096, prompt: "" },
  },
  claude: {
    label: "Claude",
    description: "Anthropic Claude model",
    category: "ai",
    icon: "Sparkles",
    color: "#D97706",
    inputs: 1,
    outputs: 1,
    defaultData: { model: "claude-3-5-sonnet", temperature: 0.7, maxTokens: 4096, prompt: "" },
  },
  gemini: {
    label: "Gemini",
    description: "Google Gemini model",
    category: "ai",
    icon: "Gem",
    color: "#4285F4",
    inputs: 1,
    outputs: 1,
    defaultData: { model: "gemini-pro", temperature: 0.7, maxTokens: 4096, prompt: "" },
  },
  deepseek: {
    label: "DeepSeek",
    description: "DeepSeek AI model",
    category: "ai",
    icon: "Zap",
    color: "#6366F1",
    inputs: 1,
    outputs: 1,
    defaultData: { model: "deepseek-chat", temperature: 0.7, maxTokens: 4096, prompt: "" },
  },
  ifElse: {
    label: "If/Else",
    description: "Conditional branching",
    category: "logic",
    icon: "GitBranch",
    color: "#7C3AED",
    inputs: 1,
    outputs: 2,
    defaultData: { condition: "", trueLabel: "True", falseLabel: "False" },
  },
  switch: {
    label: "Switch",
    description: "Multi-way branching",
    category: "logic",
    icon: "Route",
    color: "#8B5CF6",
    inputs: 1,
    outputs: 4,
    defaultData: { cases: ["case1", "case2", "case3", "default"] },
  },
  loop: {
    label: "Loop",
    description: "Iterate over items",
    category: "logic",
    icon: "Repeat",
    color: "#A855F7",
    inputs: 1,
    outputs: 1,
    defaultData: { maxIterations: 10, batchSize: 1 },
  },
  merge: {
    label: "Merge",
    description: "Combine multiple inputs",
    category: "logic",
    icon: "Merge",
    color: "#9333EA",
    inputs: 3,
    outputs: 1,
    defaultData: { strategy: "concat" },
  },
  postgresql: {
    label: "PostgreSQL",
    description: "SQL database query",
    category: "data",
    icon: "Database",
    color: "#336791",
    inputs: 1,
    outputs: 1,
    defaultData: { query: "SELECT * FROM table", connection: "" },
  },
  mongodb: {
    label: "MongoDB",
    description: "NoSQL document store",
    category: "data",
    icon: "Leaf",
    color: "#47A248",
    inputs: 1,
    outputs: 1,
    defaultData: { collection: "", operation: "find", filter: "{}" },
  },
  redis: {
    label: "Redis",
    description: "In-memory cache",
    category: "data",
    icon: "HardDrive",
    color: "#DC382D",
    inputs: 1,
    outputs: 1,
    defaultData: { key: "", operation: "get", ttl: 3600 },
  },
  vectorDb: {
    label: "Vector DB",
    description: "Semantic search store",
    category: "data",
    icon: "Network",
    color: "#06B6D4",
    inputs: 1,
    outputs: 1,
    defaultData: { index: "", topK: 5, threshold: 0.7 },
  },
  gmail: {
    label: "Gmail",
    description: "Send/receive emails",
    category: "communication",
    icon: "Mail",
    color: "#EA4335",
    inputs: 1,
    outputs: 1,
    defaultData: { to: "", subject: "", body: "" },
  },
  slack: {
    label: "Slack",
    description: "Slack messaging",
    category: "communication",
    icon: "MessageSquare",
    color: "#4A154B",
    inputs: 1,
    outputs: 1,
    defaultData: { channel: "", message: "" },
  },
  whatsapp: {
    label: "WhatsApp",
    description: "WhatsApp messaging",
    category: "communication",
    icon: "Phone",
    color: "#25D366",
    inputs: 1,
    outputs: 1,
    defaultData: { phoneNumber: "", message: "" },
  },
  discord: {
    label: "Discord",
    description: "Discord bot messaging",
    category: "communication",
    icon: "Gamepad2",
    color: "#5865F2",
    inputs: 1,
    outputs: 1,
    defaultData: { channelId: "", message: "" },
  },
  s3: {
    label: "S3",
    description: "AWS S3 storage",
    category: "storage",
    icon: "Cloud",
    color: "#FF9900",
    inputs: 1,
    outputs: 1,
    defaultData: { bucket: "", key: "", operation: "upload" },
  },
  googleDrive: {
    label: "Google Drive",
    description: "Google Drive storage",
    category: "storage",
    icon: "FolderOpen",
    color: "#4285F4",
    inputs: 1,
    outputs: 1,
    defaultData: { folderId: "", fileName: "" },
  },
  dropbox: {
    label: "Dropbox",
    description: "Dropbox file storage",
    category: "storage",
    icon: "Box",
    color: "#0061FF",
    inputs: 1,
    outputs: 1,
    defaultData: { path: "", operation: "upload" },
  },
  delay: {
    label: "Delay",
    description: "Wait before continuing",
    category: "utility",
    icon: "Clock",
    color: "#71717A",
    inputs: 1,
    outputs: 1,
    defaultData: { duration: 1000, unit: "ms" },
  },
  formatter: {
    label: "Formatter",
    description: "Transform data format",
    category: "utility",
    icon: "FileJson",
    color: "#71717A",
    inputs: 1,
    outputs: 1,
    defaultData: { format: "json", template: "" },
  },
  parser: {
    label: "Parser",
    description: "Parse structured data",
    category: "utility",
    icon: "FileCode",
    color: "#71717A",
    inputs: 1,
    outputs: 1,
    defaultData: { type: "json", schema: "" },
  },
};

export const NODE_CATEGORIES = [
  { id: "ai", label: "AI Nodes", color: "#7C3AED" },
  { id: "logic", label: "Logic Nodes", color: "#8B5CF6" },
  { id: "data", label: "Data Nodes", color: "#06B6D4" },
  { id: "communication", label: "Communication", color: "#EC4899" },
  { id: "storage", label: "Storage", color: "#F59E0B" },
  { id: "utility", label: "Utilities", color: "#71717A" },
] as const;

export function getNodesByCategory(category: string): NodeType[] {
  return (Object.entries(NODE_REGISTRY) as [NodeType, NodeConfig][])
    .filter(([, config]) => config.category === category)
    .map(([type]) => type);
}
